#dist: bionic
language: php

php:
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
  - vendor/bin/phpstan analyse --level=5 ./src/
  - vendor/bin/phpunit -c phpunit.xml

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover .coverage.xml
